[2021-02-23 14:57:42,358] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-02-22T00:00:00+00:00 [queued]>
[2021-02-23 14:57:43,624] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-02-22T00:00:00+00:00 [queued]>
[2021-02-23 14:57:43,633] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:57:43,635] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-23 14:57:43,641] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:57:43,764] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_2> on 2021-02-22T00:00:00+00:00
[2021-02-23 14:57:44,085] {standard_task_runner.py:52} INFO - Started process 136 to run task
[2021-02-23 14:57:44,467] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_2', '2021-02-22T00:00:00+00:00', '--job-id', '41', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpe4nbyh59', '--error-file', '/tmp/tmphf3qa2hl']
[2021-02-23 14:57:44,504] {standard_task_runner.py:77} INFO - Job 41: Subtask runme_2
[2021-02-23 14:57:47,011] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_2 2021-02-22T00:00:00+00:00 [running]> on host 0513e3a4eab6
[2021-02-23 14:57:48,491] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_2
AIRFLOW_CTX_EXECUTION_DATE=2021-02-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-22T00:00:00+00:00
[2021-02-23 14:57:48,505] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-23 14:57:48,515] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_2__20210222" && sleep 1
[2021-02-23 14:57:48,951] {bash.py:169} INFO - Output:
[2021-02-23 14:57:48,974] {bash.py:173} INFO - example_bash_operator__runme_2__20210222
[2021-02-23 14:57:50,055] {bash.py:177} INFO - Command exited with return code 0
[2021-02-23 14:57:50,626] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_2, execution_date=20210222T000000, start_date=20210223T145743, end_date=20210223T145750
[2021-02-23 14:57:51,886] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-23 14:57:52,013] {local_task_job.py:146} INFO - Task exited with return code 0
