[2021-02-23 14:56:37,982] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-23 14:56:41,704] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-23 14:56:41,731] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:56:41,740] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-23 14:56:41,746] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:56:44,667] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_0> on 2021-02-21T00:00:00+00:00
[2021-02-23 14:56:44,744] {standard_task_runner.py:52} INFO - Started process 73 to run task
[2021-02-23 14:56:44,856] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2021-02-21T00:00:00+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpoypxr7ip', '--error-file', '/tmp/tmpu40q4fn7']
[2021-02-23 14:56:44,879] {standard_task_runner.py:77} INFO - Job 16: Subtask runme_0
[2021-02-23 14:56:45,990] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_0 2021-02-21T00:00:00+00:00 [running]> on host 0513e3a4eab6
[2021-02-23 14:56:47,376] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_0
AIRFLOW_CTX_EXECUTION_DATE=2021-02-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-21T00:00:00+00:00
[2021-02-23 14:56:47,389] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-23 14:56:47,534] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_0__20210221" && sleep 1
[2021-02-23 14:56:47,835] {bash.py:169} INFO - Output:
[2021-02-23 14:56:47,848] {bash.py:173} INFO - example_bash_operator__runme_0__20210221
[2021-02-23 14:56:48,889] {bash.py:177} INFO - Command exited with return code 0
[2021-02-23 14:56:49,663] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20210221T000000, start_date=20210223T145640, end_date=20210223T145649
[2021-02-23 14:56:50,716] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-02-23 14:56:50,764] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 73
[2021-02-23 14:56:51,125] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-23 14:56:51,127] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-02-23 14:56:51,385] {process_utils.py:66} INFO - Process psutil.Process(pid=73, status='terminated', exitcode=1, started='14:56:43') (73) terminated with exit code 1
