[2021-02-23 14:56:27,800] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_xcom.push 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-23 14:56:29,531] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_xcom.push 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-23 14:56:30,269] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:56:30,306] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-23 14:56:30,337] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:56:31,860] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): push> on 2021-02-21T00:00:00+00:00
[2021-02-23 14:56:32,207] {standard_task_runner.py:52} INFO - Started process 60 to run task
[2021-02-23 14:56:32,385] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_xcom', 'push', '2021-02-21T00:00:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_xcom.py', '--cfg-path', '/tmp/tmp_p5r2kw3', '--error-file', '/tmp/tmpt4fuq5pk']
[2021-02-23 14:56:32,488] {standard_task_runner.py:77} INFO - Job 4: Subtask push
[2021-02-23 14:56:35,748] {logging_mixin.py:104} INFO - Running <TaskInstance: example_xcom.push 2021-02-21T00:00:00+00:00 [running]> on host 0513e3a4eab6
[2021-02-23 14:56:39,925] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_xcom
AIRFLOW_CTX_TASK_ID=push
AIRFLOW_CTX_EXECUTION_DATE=2021-02-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-21T00:00:00+00:00
[2021-02-23 14:56:42,134] {python.py:118} INFO - Done. Returned value was: None
[2021-02-23 14:56:44,095] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_xcom, task_id=push, execution_date=20210221T000000, start_date=20210223T145628, end_date=20210223T145644
[2021-02-23 14:56:46,313] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-02-23 14:56:46,366] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-02-23 14:56:46,407] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 60
[2021-02-23 14:56:46,536] {process_utils.py:66} INFO - Process psutil.Process(pid=60, status='terminated', exitcode=0, started='14:56:31') (60) terminated with exit code 0
